### ISSUE TITLE
Defeito ao estilizar 

### ISSUE THREAD

**Issue by Mateus223-ti** [FreshmanStore/freshmanstore#1]
Não está reconhecendo após alterar alguma estilização via css, não alterando de nenhuma forma, logo abaixo envio a foto de como está:
  <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=0">
        <title>freshmanstore</title>
        <link rel="stylesheet" href="/css/style.css">
        <link rel="stylesheet" href="https://freshmanstore.github.io/freshmanstore/css/style.css">
        <link rel="stylesheet" href="/css/reset.css">
        <link rel="stylesheet" href="https://freshmanstore.github.io/freshmanstore/css/reset.css">
        <script src="/js/script.js"></script>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap" rel="stylesheet">
    </head>

estes dois parecem estar como base do html puxando direto do github web a estilização reset, como percebi isso? após retirar estes dois, ocorreu alteração de todo site, descentralizando todo.

**Comment by luizfelipe9627** [comment]
@Mateus223-ti Já consegui o arrumar? Qualquer coisa me envia mensagem no whats que eu te ajudo.

**Comment by elves-dev** [comment]
Arrumado.
